server:
  port: 8100

spring:
  application:
    name: registry-service

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false           #false表示自己就是注册中心，职责是维护服务实例，不需要去检索服务
    register-with-eureka: false     #是否将自己注册到注册中心
